CREATE TABLE raw_data.api_repos_issues (
    repository_url TEXT ,
    labels_url TEXT,
    comments_url TEXT,
    events_url TEXT,
    html_url TEXT,
    issues_id INT ,
    node_id TEXT,
    number INT,
    title TEXT,
    state VARCHAR(10),
    locked BOOLEAN DEFAULT FALSE,
    comments INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    author_association VARCHAR(50),
    body TEXT,
    timeline_url TEXT,
    state_reason varchar(50),
    login_user VARCHAR(70),
    called_at TIMESTAMPTZ,
    repo_full_name TEXT
);
