CREATE TABLE raw_data.api_orgs (
  orgs_id INTEGER,
  node_id VARCHAR(50),
  name VARCHAR(50),
  description TEXT ,
  company VARCHAR(50) ,
  blog TEXT ,
  location VARCHAR(50) ,
  email VARCHAR(50) ,
  twitter_username VARCHAR(50) ,
  followers INTEGER,
  following INTEGER,
  is_verified BOOLEAN,
  has_organization_projects BOOLEAN,
  has_repository_projects BOOLEAN,
  public_repos INTEGER,
  public_gists INTEGER,
  html_url TEXT,
  avatar_url TEXT,
  type VARCHAR(30),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  called_at TIMESTAMP
);
