CREATE TABLE raw_data.api_orgs (
  id SERIAL PRIMARY KEY,
  orgs_id INTEGER NOT NULL,
  node_id VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description TEXT NULL,
  company VARCHAR(50) NULL,
  blog TEXT NULL,
  location VARCHAR(50) NULL,
  email VARCHAR(50) NULL,
  twitter_username VARCHAR(50) NULL,
  followers INTEGER NOT NULL,
  following INTEGER NOT NULL,
  is_verified BOOLEAN NOT NULL,
  has_organization_projects BOOLEAN NOT NULL,
  has_repository_projects BOOLEAN NOT NULL,
  public_repos INTEGER NOT NULL,
  public_gists INTEGER NOT NULL,
  html_url TEXT NOT NULL,
  avatar_url TEXT NOT NULL,
  type VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  called_at TIMESTAMP NOT NULL
);
