CREATE TABLE raw_data.api_users (
  users_id INTEGER,
  node_id VARCHAR(50),
  name VARCHAR(50),
  company VARCHAR(50) NULL,
  blog TEXT NULL,
  location VARCHAR(50) NULL,
  email VARCHAR(50) NULL,
  bio TEXT NULL,
  twitter_username VARCHAR(50) NULL,
  followers INTEGER,
  following INTEGER,
  public_repos INTEGER,
  public_gists INTEGER,
  html_url TEXT,
  avatar_url TEXT,
  type VARCHAR(30),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  called_at TIMESTAMP
);
