CREATE TABLE raw_data.api_repos (
	repo_id INTEGER,
	node_id VARCHAR(255),
	owner_id INTEGER,
	name VARCHAR(255),
	full_name VARCHAR(255),
	description TEXT,
	private BOOLEAN,
	html_url TEXT,
	url TEXT,
	homepage TEXT,
	created_at TIMESTAMP,
	updated_at TIMESTAMP,
	pushed_at TIMESTAMP,
	called_at TIMESTAMP,
	size INTEGER,
	stargazers_count INTEGER,
	forks_count INTEGER,
	open_issues_count INTEGER,
	language VARCHAR(50),
	archived BOOLEAN,
	disabled BOOLEAN,
	fork BOOLEAN,
	allow_forking BOOLEAN,
	license TEXT
);
