CREATE TABLE raw_data.api_repos_commits (
	sha	varchar(255) ,
	node_id	varchar(255) ,
	commit_author_name	varchar(70)	,
	commit_author_email	varchar(70)	,
	commit_author_date	timestamp ,
	commit_committer_name varchar(50) ,
	commit_committer_email varchar(70) ,
	commit_committer_date timestamp ,
	commit_message text ,
	author_login varchar(255) ,
	author_id varchar(255) ,
	author_node_id	varchar(255) ,
	author_site_admin boolean ,
	committer_login	varchar(70) ,
	committer_id varchar(70) ,
	committer_node_id varchar(255) ,
	committer_site_admin boolean ,
	repo_full_name varchar(255) ,
	called_at timestamp
);
