CREATE TABLE adhoc.api_repos_commits (
	sha	varchar(255) PRIMARY KEY NOT NULL,
	node_id	varchar(255) NOT NULL,
	commit_author_name	varchar(70)	NOT NULL,
	commit_author_email	varchar(70)	NULL,
	commit_author_date	timestamp NOT NULL,
	commit_committer_name varchar(50) NOT NULL,
	commit_committer_email varchar(70) NULL,
	commit_committer_date timestamp NOT NULL,
	commit_message text NOT NULL,
	author_login varchar(255) NULL,
	author_id varchar(255) NULL,
	author_node_id	varchar(255) NULL,
	author_site_admin boolean NULL,
	committer_login	varchar(70) NULL,
	committer_id varchar(70) NULL,
	committer_node_id varchar(255) NULL,
	committer_site_admin boolean NULL,
	repo_full_name varchar(255) NOT NULL,
	called_at timestamp	NOT NULL
);
