CREATE TABLE adhoc.api_repos_issues (
    id SERIAL PRIMARY KEY,
    repository_url TEXT NOT NULL,
    labels_url TEXT,
    comments_url TEXT,
    events_url TEXT,
    html_url TEXT,
    issues_id INT NOT NULL,
    node_id VARCHAR(255),
    number INT,
    title VARCHAR(255),
    state VARCHAR(10),
    locked BOOLEAN DEFAULT FALSE,
    comments INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    author_association VARCHAR(50),
    body TEXT,
    timeline_url TEXT,
    state_reason VARCHAR(100)[],
    login_user VARCHAR(70),
    called_at TIMESTAMPTZ,
    repo_full_name VARCHAR(255) NOT NULL
);
